# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI Build

on:
  push:
    branches:
      - '**'

jobs:
  checks:
    name: Static source code checks/validation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade tox

    - name: Static Code checks/validation
      run: |
        make pre-commit
        make linter
        make mypy

  tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: checks
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        python-version: [3.6, 3.7, 3.8, 3.9, pypy3]
        exclude:
          # conserve some osx builders
          - python-version: 3.6
            os: macos-latest
          # conserve some osx builders
          - python-version: 3.9
            os: macos-latest
        include:
          - python-version: 3.6
            os: ubuntu-latest
            tox-target: py36
          - python-version: 3.7
            os: ubuntu-latest
            tox-target: py37
          - python-version: 3.8
            os: ubuntu-latest
            tox-target: py38
          - python-version: 3.9
            os: ubuntu-latest
            tox-target: py39
          - python-version: pypy3
            os: ubuntu-latest
            tox-target: pypy
          - python-version: 3.7
            os: macos-latest
            tox-target: py37
          - python-version: 3.8
            os: macos-latest
            tox-target: py38
          - python-version: pypy3
            os: macos-latest
            tox-target: pypy

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade tox

    - name: Run unit tests
      env:
        TOXENV: ${{ matrix.tox-target }}
      run: |
        make test


  coverage:
    name: Check python source code coverage
    runs-on: ubuntu-latest
    needs: tests

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade tox

    - name: Check python source code coverage
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        make coverage
        pip install codecov>=1.4.0
        codecov
