# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI Build

on:
  push:
    branches:
      - '**'

jobs:
  checks:
    name: Check source code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade tox

    - name: Run pre-commit hooks
      run: |
        make pre-commit

    - name: Python style guide enforcement
      run: |
        make linter

    - name: Static Typing checks
      run: |
        make mypy

    - name: Run unit tests
      run: |
        make test

    - name: Check python source code coverage
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        make coverage
        pip install codecov>=1.4.0
        codecov

    - name: Check package build
      run: |
        make build
