# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python source code validation

on:
  push:
    branches:
      - '**'

jobs:
  checks:
    name: Check source code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade tox

    - name: Validate python sorce code
      run: |
        make validate

    - name: Run unit tests
      run: |
        make test

    - name: Check python source code coverage
      run: |
        make coverage

    - name: Check package build
      run: |
        make build
